source 'http://rubygems.org'
#ruby '2.0.0'
gem 'foreman'
gem 'activerecord'
gem 'parse-ruby-client'
gem 'eventmachine'
#gem 'sqlite3'
gem 'rake'
#for db migrate
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'pg'
